global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape métriques Docker (daemon.json doit avoir metrics-addr configuré)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']


  # Scrape node_exporter (métriques système hôte)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
