{
 "title": "Specific Containers Health",
 "tags": [
  "docker",
  "containers",
  "health",
  "specific"
 ],
 "panels": [
  {
   "title": "Container State - Specific Containers",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=~\"running|paused|stopped\", name=~\"postgres_container|debezium_container|redpanda_container\"}"
    }
   ]
  },
  {
   "title": "Memory Usage - Specific Containers",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{name=~\"postgres_container|debezium_container|redpanda_container\"}"
    }
   ]
  },
  {
   "title": "CPU Usage - Specific Containers",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_sum{name=~\"postgres_container|debezium_container|redpanda_container\",action=\"start\"} / engine_daemon_container_actions_seconds_count{name=~\"postgres_container|debezium_container|redpanda_container\",action=\"start\"} * 100"
    }
   ]
  }
 ]
}